/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceInput {
  'status' : AttendanceStatus,
  'attendeeName' : string,
  'attendeeType' : AttendeeType,
  'date' : string,
  'attendeeId' : string,
  'className' : [] | [string],
}
export interface AttendanceRecord {
  'id' : string,
  'status' : AttendanceStatus,
  'attendeeName' : string,
  'attendeeType' : AttendeeType,
  'date' : string,
  'createdAt' : Timestamp,
  'markedBy' : string,
  'attendeeId' : string,
  'className' : [] | [string],
}
export type AttendanceStatus = { 'Leave' : null } |
  { 'Present' : null } |
  { 'Absent' : null };
export interface AttendanceSummary {
  'attendeeName' : string,
  'present' : bigint,
  'totalDays' : bigint,
  'leave' : bigint,
  'absent' : bigint,
  'attendeeId' : string,
  'className' : [] | [string],
  'percentage' : number,
}
export type AttendeeType = { 'Teacher' : null } |
  { 'Student' : null };
export interface DashboardStats {
  'rejectedLeads' : bigint,
  'activeStudents' : bigint,
  'convertedLeads' : bigint,
  'totalStudents' : bigint,
  'followUpLeads' : bigint,
  'totalLeads' : bigint,
  'newLeads' : bigint,
  'newLeadsToday' : bigint,
  'contactedLeads' : bigint,
}
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface ExamResult {
  'id' : string,
  'studentId' : string,
  'studentName' : string,
  'subjects' : Array<SubjectMark>,
  'createdAt' : Timestamp,
  'totalObtained' : bigint,
  'totalMaximum' : bigint,
  'grade' : Grade,
  'examName' : string,
  'className' : string,
  'percentage' : number,
}
export interface ExamResultInput {
  'studentId' : string,
  'studentName' : string,
  'subjects' : Array<SubjectMark>,
  'examName' : string,
  'className' : string,
}
export type ExpenseCategory = { 'Salary' : null } |
  { 'Miscellaneous' : null } |
  { 'Maintenance' : null } |
  { 'Transport' : null } |
  { 'Utilities' : null };
export interface FeePayment {
  'id' : string,
  'status' : FeeStatus,
  'netAmount' : bigint,
  'studentId' : string,
  'studentName' : string,
  'fine' : bigint,
  'createdAt' : Timestamp,
  'installmentNo' : [] | [bigint],
  'paidDate' : [] | [string],
  'discount' : bigint,
  'receiptNo' : string,
  'amount' : bigint,
  'className' : string,
  'totalInstallments' : [] | [bigint],
}
export interface FeePaymentInput {
  'studentId' : string,
  'studentName' : string,
  'installmentNo' : [] | [bigint],
  'discount' : bigint,
  'amount' : bigint,
  'className' : string,
  'totalInstallments' : [] | [bigint],
}
export type FeeStatus = { 'PartiallyPaid' : null } |
  { 'Late' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export type Grade = { 'A' : null } |
  { 'B' : null } |
  { 'C' : null } |
  { 'D' : null } |
  { 'F' : null } |
  { 'APlusPlus' : null } |
  { 'BPlus' : null } |
  { 'APlus' : null } |
  { 'CPlus' : null };
export type IncomeCategory = { 'OtherFee' : null } |
  { 'TransportFee' : null } |
  { 'AdmissionFee' : null } |
  { 'TuitionFee' : null };
export interface Lead {
  'id' : LeadId,
  'status' : LeadStatus,
  'assignedCounsellor' : [] | [Principal],
  'name' : string,
  'createdAt' : Timestamp,
  'classInterested' : string,
  'email' : string,
  'updatedAt' : Timestamp,
  'message' : string,
  'notes' : string,
  'phone' : string,
}
export interface LeadExportRow {
  'id' : LeadId,
  'status' : string,
  'assignedCounsellor' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'classInterested' : string,
  'email' : string,
  'updatedAt' : Timestamp,
  'message' : string,
  'notes' : string,
  'phone' : string,
}
export type LeadId = bigint;
export interface LeadInput {
  'status' : LeadStatus,
  'assignedCounsellor' : [] | [Principal],
  'name' : string,
  'classInterested' : string,
  'email' : string,
  'message' : string,
  'notes' : string,
  'phone' : string,
}
export type LeadStatus = { 'New' : null } |
  { 'FollowUp' : null } |
  { 'Contacted' : null } |
  { 'Converted' : null } |
  { 'Rejected' : null };
export interface MockTest {
  'id' : string,
  'status' : TestStatus,
  'totalMarks' : bigint,
  'title' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'durationMinutes' : bigint,
  'negativeMarkingEnabled' : boolean,
  'questionIds' : Array<string>,
  'passingPercentage' : number,
  'className' : string,
}
export interface MockTestInput {
  'totalMarks' : bigint,
  'title' : string,
  'subject' : string,
  'durationMinutes' : bigint,
  'negativeMarkingEnabled' : boolean,
  'passingPercentage' : number,
  'className' : string,
}
export interface MonthlyReport {
  'month' : string,
  'year' : bigint,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'profit' : bigint,
}
export interface QRSession {
  'token' : string,
  'active' : boolean,
  'expiresAt' : bigint,
  'date' : string,
  'classId' : string,
}
export interface Question {
  'id' : string,
  'marks' : bigint,
  'negativeMarking' : boolean,
  'correctOptionId' : string,
  'difficulty' : Difficulty,
  'text' : string,
  'negativePenalty' : number,
  'options' : Array<QuestionOption>,
}
export interface QuestionInput {
  'marks' : bigint,
  'negativeMarking' : boolean,
  'correctOptionId' : string,
  'difficulty' : Difficulty,
  'text' : string,
  'negativePenalty' : number,
  'options' : Array<QuestionOption>,
}
export interface QuestionOption { 'id' : string, 'text' : string }
export type Role = { 'AdmissionCounsellor' : null } |
  { 'Parent' : null } |
  { 'Teacher' : null } |
  { 'SuperAdmin' : null } |
  { 'Student' : null } |
  { 'Principal' : null } |
  { 'Accountant' : null };
export interface SalaryInput {
  'month' : string,
  'bonusAmount' : bigint,
  'bankDetails' : [] | [string],
  'year' : bigint,
  'deductionAmount' : bigint,
  'teacherId' : string,
  'attendancePercentage' : number,
}
export interface SalaryRecord {
  'id' : string,
  'status' : SalaryStatus,
  'month' : string,
  'bankDetails' : [] | [string],
  'createdAt' : Timestamp,
  'year' : bigint,
  'deductions' : bigint,
  'netSalary' : bigint,
  'teacherName' : string,
  'paidDate' : [] | [string],
  'teacherId' : string,
  'attendanceBonus' : bigint,
  'baseSalary' : bigint,
}
export type SalaryStatus = { 'Paid' : null } |
  { 'Pending' : null };
export interface Student {
  'id' : StudentId,
  'parentEmail' : string,
  'dateOfBirth' : string,
  'admissionDate' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'parentPhone' : string,
  'section' : string,
  'photoUrl' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'rollNumber' : string,
  'address' : string,
  'className' : string,
  'parentName' : string,
}
export interface StudentCard {
  'studentId' : string,
  'dateOfBirth' : string,
  'name' : string,
  'admissionYear' : string,
  'parentPhone' : string,
  'section' : string,
  'photoUrl' : string,
  'academicYear' : string,
  'schoolAddress' : string,
  'rollNumber' : string,
  'className' : string,
  'parentName' : string,
  'schoolName' : string,
}
export type StudentId = bigint;
export interface StudentInput {
  'parentEmail' : string,
  'dateOfBirth' : string,
  'admissionDate' : Timestamp,
  'name' : string,
  'parentPhone' : string,
  'section' : string,
  'photoUrl' : string,
  'isActive' : boolean,
  'rollNumber' : string,
  'address' : string,
  'className' : string,
  'parentName' : string,
}
export interface SubjectMark {
  'totalMarks' : bigint,
  'subject' : string,
  'marksObtained' : bigint,
}
export interface TeacherInput {
  'name' : string,
  'designation' : string,
  'dateOfJoining' : string,
  'baseSalary' : bigint,
}
export interface TeacherRecord {
  'id' : string,
  'name' : string,
  'designation' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'dateOfJoining' : string,
  'baseSalary' : bigint,
}
export interface TestAttempt {
  'id' : string,
  'studentId' : string,
  'studentName' : string,
  'marksObtained' : number,
  'answers' : Array<[string, string]>,
  'submittedAt' : Timestamp,
  'timeTaken' : bigint,
  'testId' : string,
  'className' : string,
  'percentage' : number,
  'passed' : boolean,
}
export interface TestAttemptInput {
  'answers' : Array<[string, string]>,
  'timeTaken' : bigint,
  'testId' : string,
}
export type TestStatus = { 'Closed' : null } |
  { 'Draft' : null } |
  { 'Published' : null };
export type Timestamp = bigint;
export interface Transaction {
  'id' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'reference' : [] | [string],
  'description' : string,
  'txType' : TransactionType,
  'incomeCategory' : [] | [IncomeCategory],
  'amount' : bigint,
  'expenseCategory' : [] | [ExpenseCategory],
}
export interface TransactionInput {
  'date' : string,
  'reference' : [] | [string],
  'description' : string,
  'txType' : TransactionType,
  'incomeCategory' : [] | [IncomeCategory],
  'amount' : bigint,
  'expenseCategory' : [] | [ExpenseCategory],
}
export type TransactionType = { 'Income' : null } |
  { 'Expense' : null };
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
}
export interface _SERVICE {
  'addQuestion' : ActorMethod<[string, QuestionInput], Question>,
  'assignRole' : ActorMethod<[Principal, Role, string], undefined>,
  'bootstrapSuperAdmin' : ActorMethod<[string], undefined>,
  'bulkMarkAttendance' : ActorMethod<
    [Array<AttendanceInput>],
    Array<AttendanceRecord>
  >,
  'changePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createFeePayment' : ActorMethod<[FeePaymentInput], FeePayment>,
  'createLead' : ActorMethod<[LeadInput], Lead>,
  'createMyTest' : ActorMethod<
    [string, string, string, bigint, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createResult' : ActorMethod<[ExamResultInput], ExamResult>,
  'createSalaryRecord' : ActorMethod<[SalaryInput], SalaryRecord>,
  'createStudent' : ActorMethod<[StudentInput], Student>,
  'createTeacher' : ActorMethod<[TeacherInput], TeacherRecord>,
  'createTest' : ActorMethod<[MockTestInput], MockTest>,
  'createTransaction' : ActorMethod<[TransactionInput], Transaction>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'exportLeads' : ActorMethod<[], Array<LeadExportRow>>,
  'filterLeadsByStatus' : ActorMethod<[LeadStatus], Array<Lead>>,
  'generateAttendanceSession' : ActorMethod<
    [string, string],
    { 'ok' : { 'token' : string, 'expiresAt' : bigint } } |
      { 'err' : string }
  >,
  'generateTeacherQRCode' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAnnualReport' : ActorMethod<[bigint], Array<MonthlyReport>>,
  'getAssignments' : ActorMethod<
    [string],
    Array<
      {
        'id' : bigint,
        'title' : string,
        'subject' : string,
        'dueDate' : string,
        'description' : string,
        'uploadedBy' : string,
      }
    >
  >,
  'getAttendance' : ActorMethod<[string], [] | [AttendanceRecord]>,
  'getAttendanceSession' : ActorMethod<[string], [] | [QRSession]>,
  'getAttendanceSummary' : ActorMethod<[string], [] | [AttendanceSummary]>,
  'getChildAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getChildFees' : ActorMethod<[string], Array<FeePayment>>,
  'getChildResults' : ActorMethod<[string], Array<ExamResult>>,
  'getClassAttendance' : ActorMethod<[string, string], Array<AttendanceRecord>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getFeePayment' : ActorMethod<[string], [] | [FeePayment]>,
  'getFeesByStudent' : ActorMethod<[string], Array<FeePayment>>,
  'getLead' : ActorMethod<[LeadId], [] | [Lead]>,
  'getMonthlyReport' : ActorMethod<[string, bigint], MonthlyReport>,
  'getMyAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyResults' : ActorMethod<[string], Array<ExamResult>>,
  'getMySalarySlips' : ActorMethod<[string], Array<SalaryRecord>>,
  'getMyTests' : ActorMethod<[string], Array<MockTest>>,
  'getParentNotices' : ActorMethod<
    [],
    Array<
      {
        'id' : string,
        'title' : string,
        'content' : string,
        'date' : string,
        'category' : string,
      }
    >
  >,
  'getQuestion' : ActorMethod<[string], [] | [Question]>,
  'getResult' : ActorMethod<[string], [] | [ExamResult]>,
  'getResultsByExam' : ActorMethod<[string], Array<ExamResult>>,
  'getResultsByStudent' : ActorMethod<[string], Array<ExamResult>>,
  'getRole' : ActorMethod<[Principal], [] | [Role]>,
  'getSalaryByTeacher' : ActorMethod<[string], Array<SalaryRecord>>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentCard' : ActorMethod<[string], [] | [StudentCard]>,
  'getStudentNotices' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'title' : string,
        'content' : string,
        'date' : string,
        'category' : string,
      }
    >
  >,
  'getTeacher' : ActorMethod<[string], [] | [TeacherRecord]>,
  'getTest' : ActorMethod<[string], [] | [MockTest]>,
  'getTestAttempts' : ActorMethod<[string], Array<TestAttempt>>,
  'getTestLeaderboard' : ActorMethod<[string], Array<TestAttempt>>,
  'getToppers' : ActorMethod<[string, string], Array<ExamResult>>,
  'getTransaction' : ActorMethod<[string], [] | [Transaction]>,
  'listAttendance' : ActorMethod<[[] | [string]], Array<AttendanceRecord>>,
  'listFeePayments' : ActorMethod<[], Array<FeePayment>>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listPendingFees' : ActorMethod<[], Array<FeePayment>>,
  'listQuestions' : ActorMethod<[string], Array<Question>>,
  'listResults' : ActorMethod<[], Array<ExamResult>>,
  'listSalaryRecords' : ActorMethod<[], Array<SalaryRecord>>,
  'listStudentCards' : ActorMethod<[], Array<StudentCard>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listTeachers' : ActorMethod<[], Array<TeacherRecord>>,
  'listTests' : ActorMethod<[], Array<MockTest>>,
  'listTransactions' : ActorMethod<
    [[] | [TransactionType]],
    Array<Transaction>
  >,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'markAttendance' : ActorMethod<[AttendanceInput], AttendanceRecord>,
  'markClassAttendance' : ActorMethod<
    [string, string, Array<{ 'status' : string, 'studentId' : string }>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'markFeePaid' : ActorMethod<[string, string], [] | [FeePayment]>,
  'markQRAttendance' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'markSalaryPaid' : ActorMethod<
    [string, string, [] | [string]],
    [] | [SalaryRecord]
  >,
  'publishTest' : ActorMethod<[string], [] | [MockTest]>,
  'revokeRole' : ActorMethod<[Principal], undefined>,
  'sendMessageToTeacher' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitMyTestAttempt' : ActorMethod<
    [string, Array<[string, string]>],
    { 'ok' : { 'total' : bigint, 'score' : bigint, 'percentage' : number } } |
      { 'err' : string }
  >,
  'submitTestAttempt' : ActorMethod<[TestAttemptInput], TestAttempt>,
  'updateFeePayment' : ActorMethod<
    [string, FeePaymentInput],
    [] | [FeePayment]
  >,
  'updateLead' : ActorMethod<[LeadId, LeadInput], [] | [Lead]>,
  'updateResult' : ActorMethod<[string, ExamResultInput], [] | [ExamResult]>,
  'updateSalaryRecord' : ActorMethod<
    [string, SalaryInput],
    [] | [SalaryRecord]
  >,
  'updateStudent' : ActorMethod<[StudentId, StudentInput], [] | [Student]>,
  'updateTeacher' : ActorMethod<[string, TeacherInput], [] | [TeacherRecord]>,
  'updateTest' : ActorMethod<[string, MockTestInput], [] | [MockTest]>,
  'uploadHomework' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'uploadMarks' : ActorMethod<
    [
      string,
      Array<
        {
          'totalMarks' : bigint,
          'studentId' : string,
          'subject' : string,
          'marksObtained' : bigint,
        }
      >,
    ],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'verifyPassword' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];