/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const QuestionOption = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
});
export const QuestionInput = IDL.Record({
  'marks' : IDL.Nat,
  'negativeMarking' : IDL.Bool,
  'correctOptionId' : IDL.Text,
  'difficulty' : Difficulty,
  'text' : IDL.Text,
  'negativePenalty' : IDL.Float64,
  'options' : IDL.Vec(QuestionOption),
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'marks' : IDL.Nat,
  'negativeMarking' : IDL.Bool,
  'correctOptionId' : IDL.Text,
  'difficulty' : Difficulty,
  'text' : IDL.Text,
  'negativePenalty' : IDL.Float64,
  'options' : IDL.Vec(QuestionOption),
});
export const Role = IDL.Variant({
  'AdmissionCounsellor' : IDL.Null,
  'Parent' : IDL.Null,
  'Teacher' : IDL.Null,
  'SuperAdmin' : IDL.Null,
  'Student' : IDL.Null,
  'Principal' : IDL.Null,
  'Accountant' : IDL.Null,
});
export const AttendanceStatus = IDL.Variant({
  'Leave' : IDL.Null,
  'Present' : IDL.Null,
  'Absent' : IDL.Null,
});
export const AttendeeType = IDL.Variant({
  'Teacher' : IDL.Null,
  'Student' : IDL.Null,
});
export const AttendanceInput = IDL.Record({
  'status' : AttendanceStatus,
  'attendeeName' : IDL.Text,
  'attendeeType' : AttendeeType,
  'date' : IDL.Text,
  'attendeeId' : IDL.Text,
  'className' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : AttendanceStatus,
  'attendeeName' : IDL.Text,
  'attendeeType' : AttendeeType,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'markedBy' : IDL.Text,
  'attendeeId' : IDL.Text,
  'className' : IDL.Opt(IDL.Text),
});
export const FeePaymentInput = IDL.Record({
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'installmentNo' : IDL.Opt(IDL.Nat),
  'discount' : IDL.Nat,
  'amount' : IDL.Nat,
  'className' : IDL.Text,
  'totalInstallments' : IDL.Opt(IDL.Nat),
});
export const FeeStatus = IDL.Variant({
  'PartiallyPaid' : IDL.Null,
  'Late' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FeePayment = IDL.Record({
  'id' : IDL.Text,
  'status' : FeeStatus,
  'netAmount' : IDL.Nat,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'fine' : IDL.Nat,
  'createdAt' : Timestamp,
  'installmentNo' : IDL.Opt(IDL.Nat),
  'paidDate' : IDL.Opt(IDL.Text),
  'discount' : IDL.Nat,
  'receiptNo' : IDL.Text,
  'amount' : IDL.Nat,
  'className' : IDL.Text,
  'totalInstallments' : IDL.Opt(IDL.Nat),
});
export const LeadStatus = IDL.Variant({
  'New' : IDL.Null,
  'FollowUp' : IDL.Null,
  'Contacted' : IDL.Null,
  'Converted' : IDL.Null,
  'Rejected' : IDL.Null,
});
export const LeadInput = IDL.Record({
  'status' : LeadStatus,
  'assignedCounsellor' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'classInterested' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadId = IDL.Nat;
export const Lead = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'assignedCounsellor' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'classInterested' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'message' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubjectMark = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'marksObtained' : IDL.Nat,
});
export const ExamResultInput = IDL.Record({
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'subjects' : IDL.Vec(SubjectMark),
  'examName' : IDL.Text,
  'className' : IDL.Text,
});
export const Grade = IDL.Variant({
  'A' : IDL.Null,
  'B' : IDL.Null,
  'C' : IDL.Null,
  'D' : IDL.Null,
  'F' : IDL.Null,
  'APlusPlus' : IDL.Null,
  'BPlus' : IDL.Null,
  'APlus' : IDL.Null,
  'CPlus' : IDL.Null,
});
export const ExamResult = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'subjects' : IDL.Vec(SubjectMark),
  'createdAt' : Timestamp,
  'totalObtained' : IDL.Nat,
  'totalMaximum' : IDL.Nat,
  'grade' : Grade,
  'examName' : IDL.Text,
  'className' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const SalaryInput = IDL.Record({
  'month' : IDL.Text,
  'bonusAmount' : IDL.Nat,
  'bankDetails' : IDL.Opt(IDL.Text),
  'year' : IDL.Nat,
  'deductionAmount' : IDL.Nat,
  'teacherId' : IDL.Text,
  'attendancePercentage' : IDL.Float64,
});
export const SalaryStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const SalaryRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : SalaryStatus,
  'month' : IDL.Text,
  'bankDetails' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'deductions' : IDL.Nat,
  'netSalary' : IDL.Nat,
  'teacherName' : IDL.Text,
  'paidDate' : IDL.Opt(IDL.Text),
  'teacherId' : IDL.Text,
  'attendanceBonus' : IDL.Nat,
  'baseSalary' : IDL.Nat,
});
export const StudentInput = IDL.Record({
  'parentEmail' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'admissionDate' : Timestamp,
  'name' : IDL.Text,
  'parentPhone' : IDL.Text,
  'section' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
});
export const StudentId = IDL.Nat;
export const Student = IDL.Record({
  'id' : StudentId,
  'parentEmail' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'admissionDate' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'parentPhone' : IDL.Text,
  'section' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
});
export const TeacherInput = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'dateOfJoining' : IDL.Text,
  'baseSalary' : IDL.Nat,
});
export const TeacherRecord = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'dateOfJoining' : IDL.Text,
  'baseSalary' : IDL.Nat,
});
export const MockTestInput = IDL.Record({
  'totalMarks' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'negativeMarkingEnabled' : IDL.Bool,
  'passingPercentage' : IDL.Float64,
  'className' : IDL.Text,
});
export const TestStatus = IDL.Variant({
  'Closed' : IDL.Null,
  'Draft' : IDL.Null,
  'Published' : IDL.Null,
});
export const MockTest = IDL.Record({
  'id' : IDL.Text,
  'status' : TestStatus,
  'totalMarks' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'durationMinutes' : IDL.Nat,
  'negativeMarkingEnabled' : IDL.Bool,
  'questionIds' : IDL.Vec(IDL.Text),
  'passingPercentage' : IDL.Float64,
  'className' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'Income' : IDL.Null,
  'Expense' : IDL.Null,
});
export const IncomeCategory = IDL.Variant({
  'OtherFee' : IDL.Null,
  'TransportFee' : IDL.Null,
  'AdmissionFee' : IDL.Null,
  'TuitionFee' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'Salary' : IDL.Null,
  'Miscellaneous' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Transport' : IDL.Null,
  'Utilities' : IDL.Null,
});
export const TransactionInput = IDL.Record({
  'date' : IDL.Text,
  'reference' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'txType' : TransactionType,
  'incomeCategory' : IDL.Opt(IncomeCategory),
  'amount' : IDL.Nat,
  'expenseCategory' : IDL.Opt(ExpenseCategory),
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'reference' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'txType' : TransactionType,
  'incomeCategory' : IDL.Opt(IncomeCategory),
  'amount' : IDL.Nat,
  'expenseCategory' : IDL.Opt(ExpenseCategory),
});
export const LeadExportRow = IDL.Record({
  'id' : LeadId,
  'status' : IDL.Text,
  'assignedCounsellor' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'classInterested' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'message' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const MonthlyReport = IDL.Record({
  'month' : IDL.Text,
  'year' : IDL.Nat,
  'totalIncome' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'profit' : IDL.Int,
});
export const QRSession = IDL.Record({
  'token' : IDL.Text,
  'active' : IDL.Bool,
  'expiresAt' : IDL.Int,
  'date' : IDL.Text,
  'classId' : IDL.Text,
});
export const AttendanceSummary = IDL.Record({
  'attendeeName' : IDL.Text,
  'present' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'leave' : IDL.Nat,
  'absent' : IDL.Nat,
  'attendeeId' : IDL.Text,
  'className' : IDL.Opt(IDL.Text),
  'percentage' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'rejectedLeads' : IDL.Nat,
  'activeStudents' : IDL.Nat,
  'convertedLeads' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'followUpLeads' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'newLeads' : IDL.Nat,
  'newLeadsToday' : IDL.Nat,
  'contactedLeads' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
});
export const StudentCard = IDL.Record({
  'studentId' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'admissionYear' : IDL.Text,
  'parentPhone' : IDL.Text,
  'section' : IDL.Text,
  'photoUrl' : IDL.Text,
  'academicYear' : IDL.Text,
  'schoolAddress' : IDL.Text,
  'rollNumber' : IDL.Text,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
  'schoolName' : IDL.Text,
});
export const TestAttempt = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'marksObtained' : IDL.Float64,
  'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'submittedAt' : Timestamp,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Text,
  'className' : IDL.Text,
  'percentage' : IDL.Float64,
  'passed' : IDL.Bool,
});
export const TestAttemptInput = IDL.Record({
  'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func([IDL.Text, QuestionInput], [Question], []),
  'assignRole' : IDL.Func([IDL.Principal, Role, IDL.Text], [], []),
  'bootstrapSuperAdmin' : IDL.Func([IDL.Text], [], []),
  'bulkMarkAttendance' : IDL.Func(
      [IDL.Vec(AttendanceInput)],
      [IDL.Vec(AttendanceRecord)],
      [],
    ),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createFeePayment' : IDL.Func([FeePaymentInput], [FeePayment], []),
  'createLead' : IDL.Func([LeadInput], [Lead], []),
  'createMyTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createResult' : IDL.Func([ExamResultInput], [ExamResult], []),
  'createSalaryRecord' : IDL.Func([SalaryInput], [SalaryRecord], []),
  'createStudent' : IDL.Func([StudentInput], [Student], []),
  'createTeacher' : IDL.Func([TeacherInput], [TeacherRecord], []),
  'createTest' : IDL.Func([MockTestInput], [MockTest], []),
  'createTransaction' : IDL.Func([TransactionInput], [Transaction], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'exportLeads' : IDL.Func([], [IDL.Vec(LeadExportRow)], ['query']),
  'filterLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
  'generateAttendanceSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'token' : IDL.Text, 'expiresAt' : IDL.Int }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'generateTeacherQRCode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAnnualReport' : IDL.Func([IDL.Nat], [IDL.Vec(MonthlyReport)], ['query']),
  'getAssignments' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'title' : IDL.Text,
            'subject' : IDL.Text,
            'dueDate' : IDL.Text,
            'description' : IDL.Text,
            'uploadedBy' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(QRSession)],
      ['query'],
    ),
  'getAttendanceSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AttendanceSummary)],
      ['query'],
    ),
  'getChildAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getChildFees' : IDL.Func([IDL.Text], [IDL.Vec(FeePayment)], ['query']),
  'getChildResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
  'getClassAttendance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getFeePayment' : IDL.Func([IDL.Text], [IDL.Opt(FeePayment)], ['query']),
  'getFeesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(FeePayment)], ['query']),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getMonthlyReport' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [MonthlyReport],
      ['query'],
    ),
  'getMyAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
  'getMySalarySlips' : IDL.Func([IDL.Text], [IDL.Vec(SalaryRecord)], ['query']),
  'getMyTests' : IDL.Func([IDL.Text], [IDL.Vec(MockTest)], ['query']),
  'getParentNotices' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'title' : IDL.Text,
            'content' : IDL.Text,
            'date' : IDL.Text,
            'category' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getQuestion' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
  'getResult' : IDL.Func([IDL.Text], [IDL.Opt(ExamResult)], ['query']),
  'getResultsByExam' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
  'getResultsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'getRole' : IDL.Func([IDL.Principal], [IDL.Opt(Role)], ['query']),
  'getSalaryByTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentCard' : IDL.Func([IDL.Text], [IDL.Opt(StudentCard)], ['query']),
  'getStudentNotices' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'title' : IDL.Text,
            'content' : IDL.Text,
            'date' : IDL.Text,
            'category' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getTeacher' : IDL.Func([IDL.Text], [IDL.Opt(TeacherRecord)], ['query']),
  'getTest' : IDL.Func([IDL.Text], [IDL.Opt(MockTest)], ['query']),
  'getTestAttempts' : IDL.Func([IDL.Text], [IDL.Vec(TestAttempt)], ['query']),
  'getTestLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TestAttempt)],
      ['query'],
    ),
  'getToppers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
  'listAttendance' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'listPendingFees' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
  'listQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'listResults' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
  'listSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'listStudentCards' : IDL.Func([], [IDL.Vec(StudentCard)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(TeacherRecord)], ['query']),
  'listTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
  'listTransactions' : IDL.Func(
      [IDL.Opt(TransactionType)],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markAttendance' : IDL.Func([AttendanceInput], [AttendanceRecord], []),
  'markClassAttendance' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Record({ 'status' : IDL.Text, 'studentId' : IDL.Text })),
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'markFeePaid' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(FeePayment)], []),
  'markQRAttendance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'markSalaryPaid' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(SalaryRecord)],
      [],
    ),
  'publishTest' : IDL.Func([IDL.Text], [IDL.Opt(MockTest)], []),
  'revokeRole' : IDL.Func([IDL.Principal], [], []),
  'sendMessageToTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitMyTestAttempt' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'total' : IDL.Nat,
            'score' : IDL.Nat,
            'percentage' : IDL.Float64,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'submitTestAttempt' : IDL.Func([TestAttemptInput], [TestAttempt], []),
  'updateFeePayment' : IDL.Func(
      [IDL.Text, FeePaymentInput],
      [IDL.Opt(FeePayment)],
      [],
    ),
  'updateLead' : IDL.Func([LeadId, LeadInput], [IDL.Opt(Lead)], []),
  'updateResult' : IDL.Func(
      [IDL.Text, ExamResultInput],
      [IDL.Opt(ExamResult)],
      [],
    ),
  'updateSalaryRecord' : IDL.Func(
      [IDL.Text, SalaryInput],
      [IDL.Opt(SalaryRecord)],
      [],
    ),
  'updateStudent' : IDL.Func([StudentId, StudentInput], [IDL.Opt(Student)], []),
  'updateTeacher' : IDL.Func(
      [IDL.Text, TeacherInput],
      [IDL.Opt(TeacherRecord)],
      [],
    ),
  'updateTest' : IDL.Func([IDL.Text, MockTestInput], [IDL.Opt(MockTest)], []),
  'uploadHomework' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'uploadMarks' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(
          IDL.Record({
            'totalMarks' : IDL.Nat,
            'studentId' : IDL.Text,
            'subject' : IDL.Text,
            'marksObtained' : IDL.Nat,
          })
        ),
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'verifyPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const QuestionOption = IDL.Record({ 'id' : IDL.Text, 'text' : IDL.Text });
  const QuestionInput = IDL.Record({
    'marks' : IDL.Nat,
    'negativeMarking' : IDL.Bool,
    'correctOptionId' : IDL.Text,
    'difficulty' : Difficulty,
    'text' : IDL.Text,
    'negativePenalty' : IDL.Float64,
    'options' : IDL.Vec(QuestionOption),
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'marks' : IDL.Nat,
    'negativeMarking' : IDL.Bool,
    'correctOptionId' : IDL.Text,
    'difficulty' : Difficulty,
    'text' : IDL.Text,
    'negativePenalty' : IDL.Float64,
    'options' : IDL.Vec(QuestionOption),
  });
  const Role = IDL.Variant({
    'AdmissionCounsellor' : IDL.Null,
    'Parent' : IDL.Null,
    'Teacher' : IDL.Null,
    'SuperAdmin' : IDL.Null,
    'Student' : IDL.Null,
    'Principal' : IDL.Null,
    'Accountant' : IDL.Null,
  });
  const AttendanceStatus = IDL.Variant({
    'Leave' : IDL.Null,
    'Present' : IDL.Null,
    'Absent' : IDL.Null,
  });
  const AttendeeType = IDL.Variant({
    'Teacher' : IDL.Null,
    'Student' : IDL.Null,
  });
  const AttendanceInput = IDL.Record({
    'status' : AttendanceStatus,
    'attendeeName' : IDL.Text,
    'attendeeType' : AttendeeType,
    'date' : IDL.Text,
    'attendeeId' : IDL.Text,
    'className' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : AttendanceStatus,
    'attendeeName' : IDL.Text,
    'attendeeType' : AttendeeType,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'markedBy' : IDL.Text,
    'attendeeId' : IDL.Text,
    'className' : IDL.Opt(IDL.Text),
  });
  const FeePaymentInput = IDL.Record({
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'installmentNo' : IDL.Opt(IDL.Nat),
    'discount' : IDL.Nat,
    'amount' : IDL.Nat,
    'className' : IDL.Text,
    'totalInstallments' : IDL.Opt(IDL.Nat),
  });
  const FeeStatus = IDL.Variant({
    'PartiallyPaid' : IDL.Null,
    'Late' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FeePayment = IDL.Record({
    'id' : IDL.Text,
    'status' : FeeStatus,
    'netAmount' : IDL.Nat,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'fine' : IDL.Nat,
    'createdAt' : Timestamp,
    'installmentNo' : IDL.Opt(IDL.Nat),
    'paidDate' : IDL.Opt(IDL.Text),
    'discount' : IDL.Nat,
    'receiptNo' : IDL.Text,
    'amount' : IDL.Nat,
    'className' : IDL.Text,
    'totalInstallments' : IDL.Opt(IDL.Nat),
  });
  const LeadStatus = IDL.Variant({
    'New' : IDL.Null,
    'FollowUp' : IDL.Null,
    'Contacted' : IDL.Null,
    'Converted' : IDL.Null,
    'Rejected' : IDL.Null,
  });
  const LeadInput = IDL.Record({
    'status' : LeadStatus,
    'assignedCounsellor' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'classInterested' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  const Lead = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'assignedCounsellor' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'classInterested' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'message' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubjectMark = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'marksObtained' : IDL.Nat,
  });
  const ExamResultInput = IDL.Record({
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'subjects' : IDL.Vec(SubjectMark),
    'examName' : IDL.Text,
    'className' : IDL.Text,
  });
  const Grade = IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
    'D' : IDL.Null,
    'F' : IDL.Null,
    'APlusPlus' : IDL.Null,
    'BPlus' : IDL.Null,
    'APlus' : IDL.Null,
    'CPlus' : IDL.Null,
  });
  const ExamResult = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'subjects' : IDL.Vec(SubjectMark),
    'createdAt' : Timestamp,
    'totalObtained' : IDL.Nat,
    'totalMaximum' : IDL.Nat,
    'grade' : Grade,
    'examName' : IDL.Text,
    'className' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const SalaryInput = IDL.Record({
    'month' : IDL.Text,
    'bonusAmount' : IDL.Nat,
    'bankDetails' : IDL.Opt(IDL.Text),
    'year' : IDL.Nat,
    'deductionAmount' : IDL.Nat,
    'teacherId' : IDL.Text,
    'attendancePercentage' : IDL.Float64,
  });
  const SalaryStatus = IDL.Variant({ 'Paid' : IDL.Null, 'Pending' : IDL.Null });
  const SalaryRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : SalaryStatus,
    'month' : IDL.Text,
    'bankDetails' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'deductions' : IDL.Nat,
    'netSalary' : IDL.Nat,
    'teacherName' : IDL.Text,
    'paidDate' : IDL.Opt(IDL.Text),
    'teacherId' : IDL.Text,
    'attendanceBonus' : IDL.Nat,
    'baseSalary' : IDL.Nat,
  });
  const StudentInput = IDL.Record({
    'parentEmail' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'admissionDate' : Timestamp,
    'name' : IDL.Text,
    'parentPhone' : IDL.Text,
    'section' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const StudentId = IDL.Nat;
  const Student = IDL.Record({
    'id' : StudentId,
    'parentEmail' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'admissionDate' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'parentPhone' : IDL.Text,
    'section' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const TeacherInput = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'dateOfJoining' : IDL.Text,
    'baseSalary' : IDL.Nat,
  });
  const TeacherRecord = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'dateOfJoining' : IDL.Text,
    'baseSalary' : IDL.Nat,
  });
  const MockTestInput = IDL.Record({
    'totalMarks' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'negativeMarkingEnabled' : IDL.Bool,
    'passingPercentage' : IDL.Float64,
    'className' : IDL.Text,
  });
  const TestStatus = IDL.Variant({
    'Closed' : IDL.Null,
    'Draft' : IDL.Null,
    'Published' : IDL.Null,
  });
  const MockTest = IDL.Record({
    'id' : IDL.Text,
    'status' : TestStatus,
    'totalMarks' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'durationMinutes' : IDL.Nat,
    'negativeMarkingEnabled' : IDL.Bool,
    'questionIds' : IDL.Vec(IDL.Text),
    'passingPercentage' : IDL.Float64,
    'className' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'Income' : IDL.Null,
    'Expense' : IDL.Null,
  });
  const IncomeCategory = IDL.Variant({
    'OtherFee' : IDL.Null,
    'TransportFee' : IDL.Null,
    'AdmissionFee' : IDL.Null,
    'TuitionFee' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'Salary' : IDL.Null,
    'Miscellaneous' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Transport' : IDL.Null,
    'Utilities' : IDL.Null,
  });
  const TransactionInput = IDL.Record({
    'date' : IDL.Text,
    'reference' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'txType' : TransactionType,
    'incomeCategory' : IDL.Opt(IncomeCategory),
    'amount' : IDL.Nat,
    'expenseCategory' : IDL.Opt(ExpenseCategory),
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'reference' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'txType' : TransactionType,
    'incomeCategory' : IDL.Opt(IncomeCategory),
    'amount' : IDL.Nat,
    'expenseCategory' : IDL.Opt(ExpenseCategory),
  });
  const LeadExportRow = IDL.Record({
    'id' : LeadId,
    'status' : IDL.Text,
    'assignedCounsellor' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'classInterested' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'message' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MonthlyReport = IDL.Record({
    'month' : IDL.Text,
    'year' : IDL.Nat,
    'totalIncome' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'profit' : IDL.Int,
  });
  const QRSession = IDL.Record({
    'token' : IDL.Text,
    'active' : IDL.Bool,
    'expiresAt' : IDL.Int,
    'date' : IDL.Text,
    'classId' : IDL.Text,
  });
  const AttendanceSummary = IDL.Record({
    'attendeeName' : IDL.Text,
    'present' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'leave' : IDL.Nat,
    'absent' : IDL.Nat,
    'attendeeId' : IDL.Text,
    'className' : IDL.Opt(IDL.Text),
    'percentage' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'rejectedLeads' : IDL.Nat,
    'activeStudents' : IDL.Nat,
    'convertedLeads' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'followUpLeads' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'newLeads' : IDL.Nat,
    'newLeadsToday' : IDL.Nat,
    'contactedLeads' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
  });
  const StudentCard = IDL.Record({
    'studentId' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'admissionYear' : IDL.Text,
    'parentPhone' : IDL.Text,
    'section' : IDL.Text,
    'photoUrl' : IDL.Text,
    'academicYear' : IDL.Text,
    'schoolAddress' : IDL.Text,
    'rollNumber' : IDL.Text,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  const TestAttempt = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'marksObtained' : IDL.Float64,
    'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'submittedAt' : Timestamp,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Text,
    'className' : IDL.Text,
    'percentage' : IDL.Float64,
    'passed' : IDL.Bool,
  });
  const TestAttemptInput = IDL.Record({
    'answers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Text,
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func([IDL.Text, QuestionInput], [Question], []),
    'assignRole' : IDL.Func([IDL.Principal, Role, IDL.Text], [], []),
    'bootstrapSuperAdmin' : IDL.Func([IDL.Text], [], []),
    'bulkMarkAttendance' : IDL.Func(
        [IDL.Vec(AttendanceInput)],
        [IDL.Vec(AttendanceRecord)],
        [],
      ),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createFeePayment' : IDL.Func([FeePaymentInput], [FeePayment], []),
    'createLead' : IDL.Func([LeadInput], [Lead], []),
    'createMyTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createResult' : IDL.Func([ExamResultInput], [ExamResult], []),
    'createSalaryRecord' : IDL.Func([SalaryInput], [SalaryRecord], []),
    'createStudent' : IDL.Func([StudentInput], [Student], []),
    'createTeacher' : IDL.Func([TeacherInput], [TeacherRecord], []),
    'createTest' : IDL.Func([MockTestInput], [MockTest], []),
    'createTransaction' : IDL.Func([TransactionInput], [Transaction], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'exportLeads' : IDL.Func([], [IDL.Vec(LeadExportRow)], ['query']),
    'filterLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
    'generateAttendanceSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'token' : IDL.Text, 'expiresAt' : IDL.Int }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'generateTeacherQRCode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAnnualReport' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyReport)],
        ['query'],
      ),
    'getAssignments' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'title' : IDL.Text,
              'subject' : IDL.Text,
              'dueDate' : IDL.Text,
              'description' : IDL.Text,
              'uploadedBy' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(QRSession)],
        ['query'],
      ),
    'getAttendanceSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AttendanceSummary)],
        ['query'],
      ),
    'getChildAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getChildFees' : IDL.Func([IDL.Text], [IDL.Vec(FeePayment)], ['query']),
    'getChildResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
    'getClassAttendance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getFeePayment' : IDL.Func([IDL.Text], [IDL.Opt(FeePayment)], ['query']),
    'getFeesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(FeePayment)], ['query']),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getMonthlyReport' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [MonthlyReport],
        ['query'],
      ),
    'getMyAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
    'getMySalarySlips' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getMyTests' : IDL.Func([IDL.Text], [IDL.Vec(MockTest)], ['query']),
    'getParentNotices' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'title' : IDL.Text,
              'content' : IDL.Text,
              'date' : IDL.Text,
              'category' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getQuestion' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
    'getResult' : IDL.Func([IDL.Text], [IDL.Opt(ExamResult)], ['query']),
    'getResultsByExam' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
    'getResultsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getRole' : IDL.Func([IDL.Principal], [IDL.Opt(Role)], ['query']),
    'getSalaryByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentCard' : IDL.Func([IDL.Text], [IDL.Opt(StudentCard)], ['query']),
    'getStudentNotices' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'title' : IDL.Text,
              'content' : IDL.Text,
              'date' : IDL.Text,
              'category' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getTeacher' : IDL.Func([IDL.Text], [IDL.Opt(TeacherRecord)], ['query']),
    'getTest' : IDL.Func([IDL.Text], [IDL.Opt(MockTest)], ['query']),
    'getTestAttempts' : IDL.Func([IDL.Text], [IDL.Vec(TestAttempt)], ['query']),
    'getTestLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TestAttempt)],
        ['query'],
      ),
    'getToppers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
    'listAttendance' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'listPendingFees' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
    'listQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'listResults' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
    'listSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'listStudentCards' : IDL.Func([], [IDL.Vec(StudentCard)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(TeacherRecord)], ['query']),
    'listTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
    'listTransactions' : IDL.Func(
        [IDL.Opt(TransactionType)],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markAttendance' : IDL.Func([AttendanceInput], [AttendanceRecord], []),
    'markClassAttendance' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Record({ 'status' : IDL.Text, 'studentId' : IDL.Text })),
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'markFeePaid' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(FeePayment)], []),
    'markQRAttendance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'markSalaryPaid' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(SalaryRecord)],
        [],
      ),
    'publishTest' : IDL.Func([IDL.Text], [IDL.Opt(MockTest)], []),
    'revokeRole' : IDL.Func([IDL.Principal], [], []),
    'sendMessageToTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitMyTestAttempt' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'total' : IDL.Nat,
              'score' : IDL.Nat,
              'percentage' : IDL.Float64,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'submitTestAttempt' : IDL.Func([TestAttemptInput], [TestAttempt], []),
    'updateFeePayment' : IDL.Func(
        [IDL.Text, FeePaymentInput],
        [IDL.Opt(FeePayment)],
        [],
      ),
    'updateLead' : IDL.Func([LeadId, LeadInput], [IDL.Opt(Lead)], []),
    'updateResult' : IDL.Func(
        [IDL.Text, ExamResultInput],
        [IDL.Opt(ExamResult)],
        [],
      ),
    'updateSalaryRecord' : IDL.Func(
        [IDL.Text, SalaryInput],
        [IDL.Opt(SalaryRecord)],
        [],
      ),
    'updateStudent' : IDL.Func(
        [StudentId, StudentInput],
        [IDL.Opt(Student)],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [IDL.Text, TeacherInput],
        [IDL.Opt(TeacherRecord)],
        [],
      ),
    'updateTest' : IDL.Func([IDL.Text, MockTestInput], [IDL.Opt(MockTest)], []),
    'uploadHomework' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'uploadMarks' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(
            IDL.Record({
              'totalMarks' : IDL.Nat,
              'studentId' : IDL.Text,
              'subject' : IDL.Text,
              'marksObtained' : IDL.Nat,
            })
          ),
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'verifyPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };