/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It should not be edited manually.

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as AboutRoute } from "./routes/about";
import { Route as AcademicsRoute } from "./routes/academics";
import { Route as AdminAttendanceRoute } from "./routes/admin/attendance";
import { Route as AdminChangePasswordImport } from "./routes/admin/change-password";
import { Route as AdminFeesRoute } from "./routes/admin/fees";
import { Route as AdminFinanceRoute } from "./routes/admin/finance";
import { Route as AdminIndexRoute } from "./routes/admin/index";
import { Route as AdminLeadsRoute } from "./routes/admin/leads";
import { Route as AdminResultsRoute } from "./routes/admin/results";
import { Route as AdminSalaryRoute } from "./routes/admin/salary";
import { Route as AdminStudentsRoute } from "./routes/admin/students";
import { Route as AdminTestsRoute } from "./routes/admin/tests";
import { Route as AdmissionsRoute } from "./routes/admissions";
import { Route as BlogRoute } from "./routes/blog";
import { Route as ContactRoute } from "./routes/contact";
import { Route as FacilitiesRoute } from "./routes/facilities";
import { Route as GalleryRoute } from "./routes/gallery";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as ParentAttendanceRoute } from "./routes/parent/attendance";
import { Route as ParentFeesRoute } from "./routes/parent/fees";
// Parent portal routes
import { Route as ParentIndexRoute } from "./routes/parent/index";
import { Route as ParentMessagesRoute } from "./routes/parent/messages";
import { Route as ParentNoticesRoute } from "./routes/parent/notices";
import { Route as ParentResultsRoute } from "./routes/parent/results";
import { Route as StudentAssignmentsRoute } from "./routes/student/assignments";
import { Route as StudentAttendanceRoute } from "./routes/student/attendance";
// Student portal routes
import { Route as StudentIndexRoute } from "./routes/student/index";
import { Route as StudentNoticesRoute } from "./routes/student/notices";
import { Route as StudentResultsRoute } from "./routes/student/results";
import { Route as StudentSettingsRoute } from "./routes/student/settings";
import { Route as StudentTestsRoute } from "./routes/student/tests";
import { Route as TeacherAttendanceRoute } from "./routes/teacher/attendance";
import { Route as TeacherHomeworkRoute } from "./routes/teacher/homework";
import { Route as TeacherIdcardsRoute } from "./routes/teacher/idcards";
// Teacher portal routes
import { Route as TeacherIndexRoute } from "./routes/teacher/index";
import { Route as TeacherMarksRoute } from "./routes/teacher/marks";
import { Route as TeacherSalaryRoute } from "./routes/teacher/salary";
import { Route as TeacherTestsRoute } from "./routes/teacher/tests";

// Create/Update Routes
const IndexRouteWithChildren = IndexRoute.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);
const AboutRouteWithChildren = AboutRoute.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any);
const AdmissionsRouteWithChildren = AdmissionsRoute.update({
  path: "/admissions",
  getParentRoute: () => rootRoute,
} as any);
const AcademicsRouteWithChildren = AcademicsRoute.update({
  path: "/academics",
  getParentRoute: () => rootRoute,
} as any);
const FacilitiesRouteWithChildren = FacilitiesRoute.update({
  path: "/facilities",
  getParentRoute: () => rootRoute,
} as any);
const GalleryRouteWithChildren = GalleryRoute.update({
  path: "/gallery",
  getParentRoute: () => rootRoute,
} as any);
const BlogRouteWithChildren = BlogRoute.update({
  path: "/blog",
  getParentRoute: () => rootRoute,
} as any);
const ContactRouteWithChildren = ContactRoute.update({
  path: "/contact",
  getParentRoute: () => rootRoute,
} as any);
const LoginRouteWithChildren = LoginRoute.update({
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);
const AdminIndexRouteWithChildren = AdminIndexRoute.update({
  path: "/admin/",
  getParentRoute: () => rootRoute,
} as any);
const AdminStudentsRouteWithChildren = AdminStudentsRoute.update({
  path: "/admin/students",
  getParentRoute: () => rootRoute,
} as any);
const AdminLeadsRouteWithChildren = AdminLeadsRoute.update({
  path: "/admin/leads",
  getParentRoute: () => rootRoute,
} as any);
const AdminAttendanceRouteWithChildren = AdminAttendanceRoute.update({
  path: "/admin/attendance",
  getParentRoute: () => rootRoute,
} as any);
const AdminFeesRouteWithChildren = AdminFeesRoute.update({
  path: "/admin/fees",
  getParentRoute: () => rootRoute,
} as any);
const AdminFinanceRouteWithChildren = AdminFinanceRoute.update({
  path: "/admin/finance",
  getParentRoute: () => rootRoute,
} as any);
const AdminResultsRouteWithChildren = AdminResultsRoute.update({
  path: "/admin/results",
  getParentRoute: () => rootRoute,
} as any);
const AdminSalaryRouteWithChildren = AdminSalaryRoute.update({
  path: "/admin/salary",
  getParentRoute: () => rootRoute,
} as any);
const AdminTestsRouteWithChildren = AdminTestsRoute.update({
  path: "/admin/tests",
  getParentRoute: () => rootRoute,
} as any);
const AdminChangePasswordRoute = AdminChangePasswordImport.update({
  id: "/admin/change-password",
  path: "/admin/change-password",
  getParentRoute: () => rootRoute,
} as any);

// Parent portal routes
const ParentIndexRouteWithChildren = ParentIndexRoute.update({
  path: "/parent/",
  getParentRoute: () => rootRoute,
} as any);
const ParentAttendanceRouteWithChildren = ParentAttendanceRoute.update({
  path: "/parent/attendance",
  getParentRoute: () => rootRoute,
} as any);
const ParentFeesRouteWithChildren = ParentFeesRoute.update({
  path: "/parent/fees",
  getParentRoute: () => rootRoute,
} as any);
const ParentMessagesRouteWithChildren = ParentMessagesRoute.update({
  path: "/parent/messages",
  getParentRoute: () => rootRoute,
} as any);
const ParentNoticesRouteWithChildren = ParentNoticesRoute.update({
  path: "/parent/notices",
  getParentRoute: () => rootRoute,
} as any);
const ParentResultsRouteWithChildren = ParentResultsRoute.update({
  path: "/parent/results",
  getParentRoute: () => rootRoute,
} as any);

// Student portal routes
const StudentIndexRouteWithChildren = StudentIndexRoute.update({
  path: "/student/",
  getParentRoute: () => rootRoute,
} as any);
const StudentAssignmentsRouteWithChildren = StudentAssignmentsRoute.update({
  path: "/student/assignments",
  getParentRoute: () => rootRoute,
} as any);
const StudentAttendanceRouteWithChildren = StudentAttendanceRoute.update({
  path: "/student/attendance",
  getParentRoute: () => rootRoute,
} as any);
const StudentNoticesRouteWithChildren = StudentNoticesRoute.update({
  path: "/student/notices",
  getParentRoute: () => rootRoute,
} as any);
const StudentResultsRouteWithChildren = StudentResultsRoute.update({
  path: "/student/results",
  getParentRoute: () => rootRoute,
} as any);
const StudentSettingsRouteWithChildren = StudentSettingsRoute.update({
  path: "/student/settings",
  getParentRoute: () => rootRoute,
} as any);
const StudentTestsRouteWithChildren = StudentTestsRoute.update({
  path: "/student/tests",
  getParentRoute: () => rootRoute,
} as any);

// Teacher portal routes
const TeacherIndexRouteWithChildren = TeacherIndexRoute.update({
  path: "/teacher/",
  getParentRoute: () => rootRoute,
} as any);
const TeacherAttendanceRouteWithChildren = TeacherAttendanceRoute.update({
  path: "/teacher/attendance",
  getParentRoute: () => rootRoute,
} as any);
const TeacherHomeworkRouteWithChildren = TeacherHomeworkRoute.update({
  path: "/teacher/homework",
  getParentRoute: () => rootRoute,
} as any);
const TeacherIdcardsRouteWithChildren = TeacherIdcardsRoute.update({
  path: "/teacher/idcards",
  getParentRoute: () => rootRoute,
} as any);
const TeacherMarksRouteWithChildren = TeacherMarksRoute.update({
  path: "/teacher/marks",
  getParentRoute: () => rootRoute,
} as any);
const TeacherSalaryRouteWithChildren = TeacherSalaryRoute.update({
  path: "/teacher/salary",
  getParentRoute: () => rootRoute,
} as any);
const TeacherTestsRouteWithChildren = TeacherTestsRoute.update({
  path: "/teacher/tests",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/parent/": {
      id: "/parent/";
      path: "/parent/";
      fullPath: "/parent/";
      preLoaderRoute: typeof ParentIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/parent/attendance": {
      id: "/parent/attendance";
      path: "/parent/attendance";
      fullPath: "/parent/attendance";
      preLoaderRoute: typeof ParentAttendanceRoute;
      parentRoute: typeof rootRoute;
    };
    "/parent/fees": {
      id: "/parent/fees";
      path: "/parent/fees";
      fullPath: "/parent/fees";
      preLoaderRoute: typeof ParentFeesRoute;
      parentRoute: typeof rootRoute;
    };
    "/parent/messages": {
      id: "/parent/messages";
      path: "/parent/messages";
      fullPath: "/parent/messages";
      preLoaderRoute: typeof ParentMessagesRoute;
      parentRoute: typeof rootRoute;
    };
    "/parent/notices": {
      id: "/parent/notices";
      path: "/parent/notices";
      fullPath: "/parent/notices";
      preLoaderRoute: typeof ParentNoticesRoute;
      parentRoute: typeof rootRoute;
    };
    "/parent/results": {
      id: "/parent/results";
      path: "/parent/results";
      fullPath: "/parent/results";
      preLoaderRoute: typeof ParentResultsRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/": {
      id: "/student/";
      path: "/student/";
      fullPath: "/student/";
      preLoaderRoute: typeof StudentIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/assignments": {
      id: "/student/assignments";
      path: "/student/assignments";
      fullPath: "/student/assignments";
      preLoaderRoute: typeof StudentAssignmentsRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/attendance": {
      id: "/student/attendance";
      path: "/student/attendance";
      fullPath: "/student/attendance";
      preLoaderRoute: typeof StudentAttendanceRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/notices": {
      id: "/student/notices";
      path: "/student/notices";
      fullPath: "/student/notices";
      preLoaderRoute: typeof StudentNoticesRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/results": {
      id: "/student/results";
      path: "/student/results";
      fullPath: "/student/results";
      preLoaderRoute: typeof StudentResultsRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/settings": {
      id: "/student/settings";
      path: "/student/settings";
      fullPath: "/student/settings";
      preLoaderRoute: typeof StudentSettingsRoute;
      parentRoute: typeof rootRoute;
    };
    "/student/tests": {
      id: "/student/tests";
      path: "/student/tests";
      fullPath: "/student/tests";
      preLoaderRoute: typeof StudentTestsRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/": {
      id: "/teacher/";
      path: "/teacher/";
      fullPath: "/teacher/";
      preLoaderRoute: typeof TeacherIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/attendance": {
      id: "/teacher/attendance";
      path: "/teacher/attendance";
      fullPath: "/teacher/attendance";
      preLoaderRoute: typeof TeacherAttendanceRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/homework": {
      id: "/teacher/homework";
      path: "/teacher/homework";
      fullPath: "/teacher/homework";
      preLoaderRoute: typeof TeacherHomeworkRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/idcards": {
      id: "/teacher/idcards";
      path: "/teacher/idcards";
      fullPath: "/teacher/idcards";
      preLoaderRoute: typeof TeacherIdcardsRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/marks": {
      id: "/teacher/marks";
      path: "/teacher/marks";
      fullPath: "/teacher/marks";
      preLoaderRoute: typeof TeacherMarksRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/salary": {
      id: "/teacher/salary";
      path: "/teacher/salary";
      fullPath: "/teacher/salary";
      preLoaderRoute: typeof TeacherSalaryRoute;
      parentRoute: typeof rootRoute;
    };
    "/teacher/tests": {
      id: "/teacher/tests";
      path: "/teacher/tests";
      fullPath: "/teacher/tests";
      preLoaderRoute: typeof TeacherTestsRoute;
      parentRoute: typeof rootRoute;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRoute;
      parentRoute: typeof rootRoute;
    };
    "/admissions": {
      id: "/admissions";
      path: "/admissions";
      fullPath: "/admissions";
      preLoaderRoute: typeof AdmissionsRoute;
      parentRoute: typeof rootRoute;
    };
    "/academics": {
      id: "/academics";
      path: "/academics";
      fullPath: "/academics";
      preLoaderRoute: typeof AcademicsRoute;
      parentRoute: typeof rootRoute;
    };
    "/facilities": {
      id: "/facilities";
      path: "/facilities";
      fullPath: "/facilities";
      preLoaderRoute: typeof FacilitiesRoute;
      parentRoute: typeof rootRoute;
    };
    "/gallery": {
      id: "/gallery";
      path: "/gallery";
      fullPath: "/gallery";
      preLoaderRoute: typeof GalleryRoute;
      parentRoute: typeof rootRoute;
    };
    "/blog": {
      id: "/blog";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogRoute;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRoute;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/": {
      id: "/admin/";
      path: "/admin/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/students": {
      id: "/admin/students";
      path: "/admin/students";
      fullPath: "/admin/students";
      preLoaderRoute: typeof AdminStudentsRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/leads": {
      id: "/admin/leads";
      path: "/admin/leads";
      fullPath: "/admin/leads";
      preLoaderRoute: typeof AdminLeadsRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/fees": {
      id: "/admin/fees";
      path: "/admin/fees";
      fullPath: "/admin/fees";
      preLoaderRoute: typeof AdminFeesRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/salary": {
      id: "/admin/salary";
      path: "/admin/salary";
      fullPath: "/admin/salary";
      preLoaderRoute: typeof AdminSalaryRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/attendance": {
      id: "/admin/attendance";
      path: "/admin/attendance";
      fullPath: "/admin/attendance";
      preLoaderRoute: typeof AdminAttendanceRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/results": {
      id: "/admin/results";
      path: "/admin/results";
      fullPath: "/admin/results";
      preLoaderRoute: typeof AdminResultsRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/tests": {
      id: "/admin/tests";
      path: "/admin/tests";
      fullPath: "/admin/tests";
      preLoaderRoute: typeof AdminTestsRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/finance": {
      id: "/admin/finance";
      path: "/admin/finance";
      fullPath: "/admin/finance";
      preLoaderRoute: typeof AdminFinanceRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/change-password": {
      id: "/admin/change-password";
      path: "/admin/change-password";
      fullPath: "/admin/change-password";
      preLoaderRoute: typeof AdminChangePasswordImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree
export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  AboutRouteWithChildren,
  AdmissionsRouteWithChildren,
  AcademicsRouteWithChildren,
  FacilitiesRouteWithChildren,
  GalleryRouteWithChildren,
  BlogRouteWithChildren,
  ContactRouteWithChildren,
  LoginRouteWithChildren,
  AdminIndexRouteWithChildren,
  AdminStudentsRouteWithChildren,
  AdminLeadsRouteWithChildren,
  AdminFeesRouteWithChildren,
  AdminSalaryRouteWithChildren,
  AdminAttendanceRouteWithChildren,
  AdminResultsRouteWithChildren,
  AdminTestsRouteWithChildren,
  AdminFinanceRouteWithChildren,
  AdminChangePasswordRoute,
  // Parent portal
  ParentIndexRouteWithChildren,
  ParentAttendanceRouteWithChildren,
  ParentFeesRouteWithChildren,
  ParentMessagesRouteWithChildren,
  ParentNoticesRouteWithChildren,
  ParentResultsRouteWithChildren,
  // Student portal
  StudentIndexRouteWithChildren,
  StudentAssignmentsRouteWithChildren,
  StudentAttendanceRouteWithChildren,
  StudentNoticesRouteWithChildren,
  StudentResultsRouteWithChildren,
  StudentSettingsRouteWithChildren,
  StudentTestsRouteWithChildren,
  // Teacher portal
  TeacherIndexRouteWithChildren,
  TeacherAttendanceRouteWithChildren,
  TeacherHomeworkRouteWithChildren,
  TeacherIdcardsRouteWithChildren,
  TeacherMarksRouteWithChildren,
  TeacherSalaryRouteWithChildren,
  TeacherTestsRouteWithChildren,
]);
